function(cu_init_add_sources)
    unset(cu_source_list CACHE)
endfunction()

function(cu_add_sources)
    set(srcs)
    foreach(s IN LISTS ARGN)
        if (NOT IS_ABSOLUTE "${s}")
            get_filename_component(s "${s}" ABSOLUTE)
        endif ()
        list(APPEND srcs "${s}")
    endforeach()

    set(cu_source_list ${cu_source_list} "${srcs}" CACHE INTERNAL "")
endfunction()