function(jobrocket_init)
    unset(jobrocket_sources CACHE)
endfunction()

function(jobrocket_add_sources)
    set(srcs)
    foreach(s IN LISTS ARGN)
        if (NOT IS_ABSOLUTE "${s}")
            get_filename_component(s "${s}" ABSOLUTE)
        endif ()
        list(APPEND srcs "${s}")
    endforeach()

    set(jobrocket_sources ${jobrocket_sources} "${srcs}" CACHE INTERNAL "")
endfunction()